[env:esp32dev]
platform = platformio/espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+

lib_deps =
    mikalhart/TinyGPSPlus
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
